import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Second entry point for the module project "Generacion y clasificacion de datos".
 * 
 * This class reads the pseudo-random flat files generated by {@link GenerateInfoFiles},
 * processes the sales data, and creates two report files:
 * 1. Salesmen ranked by total money collected (descending).
 * 2. Products ranked by total quantity sold (descending).
 * 
 * Note: The assignment instructions mention the class should be named "main".
 * Java conventions recommend "Main" (UpperCamelCase). If your professor strictly 
 * requires the filename to be "main.java", please rename this file and class accordingly.
 */
public class Main {

    private static final String PRODUCTS_FILE = "products.txt";
    private static final String SALESMEN_FILE = "salesmen.txt";
    private static final String SALES_FILE_PREFIX = "sales_";
    
    private static final String SALESMEN_REPORT_FILE = "salesmen_report.csv";
    private static final String PRODUCTS_REPORT_FILE = "products_report.csv";

    public static void main(String[] args) {
        try {
            System.out.println("Starting data classification process...");

            // 1. Load reference data
            Map<Integer, Product> productsMap = loadProducts(PRODUCTS_FILE);
            if (productsMap.isEmpty()) {
                throw new IOException("No products loaded. Check " + PRODUCTS_FILE);
            }

            Map<Long, Salesman> salesmenMap = loadSalesmen(SALESMEN_FILE);
            if (salesmenMap.isEmpty()) {
                throw new IOException("No salesmen loaded. Check " + SALESMEN_FILE);
            }

            // 2. Initialize accumulators
            Map<Long, Double> salesmanMoneyMap = new HashMap<>();
            Map<Integer, Integer> productQuantityMap = new HashMap<>();

            for (Salesman salesman : salesmenMap.values()) {
                salesmanMoneyMap.put(salesman.getDocumentNumber(), 0.0);
            }
            for (Product product : productsMap.values()) {
                productQuantityMap.put(product.getId(), 0);
            }

            // 3. Process all sales files in the current directory
            File folder = new File(".");
            File[] salesFiles = folder.listFiles((dir, name) -> name.startsWith(SALES_FILE_PREFIX) && name.endsWith(".txt"));

            if (salesFiles != null) {
                for (File salesFile : salesFiles) {
                    processSalesFile(salesFile, salesmenMap, productsMap, salesmanMoneyMap, productQuantityMap);
                }
            }

            // 4. Generate sorted reports
            generateSalesmenReport(salesmenMap, salesmanMoneyMap, SALESMEN_REPORT_FILE);
            generateProductsReport(productsMap, productQuantityMap, PRODUCTS_REPORT_FILE);

            System.out.println("SUCCESS: Report files generated correctly.");
            System.out.println("  - Salesmen report: " + SALESMEN_REPORT_FILE);
            System.out.println("  - Products report: " + PRODUCTS_REPORT_FILE);

        } catch (IOException e) {
            System.out.println("ERROR: Could not process the data. Details: " + e.getMessage());
        }
    }

    private static Map<Integer, Product> loadProducts(String fileName) throws IOException {
        Map<Integer, Product> products = new HashMap<>();
        try (BufferedReader reader = new BufferedReader(new FileReader(fileName))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(";");
                if (parts.length >= 3) {
                    int id = Integer.parseInt(parts[0].trim());
                    String name = parts[1].trim();
                    double price = Double.parseDouble(parts[2].trim());
                    products.put(id, new Product(id, name, price));
                }
            }
        }
        return products;
    }

    private static Map<Long, Salesman> loadSalesmen(String fileName) throws IOException {
        Map<Long, Salesman> salesmen = new HashMap<>();
        try (BufferedReader reader = new BufferedReader(new FileReader(fileName))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(";");
                if (parts.length >= 4) {
                    String docType = parts[0].trim();
                    long docNumber = Long.parseLong(parts[1].trim());
                    String firstNames = parts[2].trim();
                    String lastNames = parts[3].trim();
                    salesmen.put(docNumber, new Salesman(docType, docNumber, firstNames, lastNames));
                }
            }
        }
        return salesmen;
    }

    private static void processSalesFile(File file, Map<Long, Salesman> salesmenMap, 
                                         Map<Integer, Product> productsMap, 
                                         Map<Long, Double> salesmanMoneyMap, 
                                         Map<Integer, Integer> productQuantityMap) throws IOException {
        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String firstLine = reader.readLine();
            if (firstLine == null) return;
            
            String[] firstParts = firstLine.split(";");
            if (firstParts.length < 2) return;
            
            long docNumber = Long.parseLong(firstParts[1].trim());
            
            if (!salesmenMap.containsKey(docNumber)) {
                System.out.println("WARNING: Salesman with document " + docNumber + " not found in " + SALESMEN_FILE);
                return;
            }

            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(";");
                if (parts.length >= 2) {
                    int productId = Integer.parseInt(parts[0].trim());
                    int quantity = Integer.parseInt(parts[1].trim());
                    
                    Product product = productsMap.get(productId);
                    if (product != null) {
                        double totalMoney = quantity * product.getPricePerUnit();
                        salesmanMoneyMap.put(docNumber, salesmanMoneyMap.get(docNumber) + totalMoney);
                        productQuantityMap.put(productId, productQuantityMap.get(productId) + quantity);
                    }
                }
            }
        }
    }

    private static void generateSalesmenReport(Map<Long, Salesman> salesmenMap, 
                                               Map<Long, Double> salesmanMoneyMap, 
                                               String fileName) throws IOException {
        List<Map.Entry<Long, Double>> list = new ArrayList<>(salesmanMoneyMap.entrySet());
        list.sort((e1, e2) -> Double.compare(e2.getValue(), e1.getValue())); // Descending order

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileName))) {
            writer.write("Nombres;Apellidos;TotalDineroRecaudado");
            writer.newLine();
            for (Map.Entry<Long, Double> entry : list) {
                Salesman salesman = salesmenMap.get(entry.getKey());
                double totalMoney = entry.getValue();
                writer.write(salesman.getFirstNames() + ";" + salesman.getLastNames() + ";" + String.format("%.2f", totalMoney));
                writer.newLine();
            }
        }
    }

    private static void generateProductsReport(Map<Integer, Product> productsMap, 
                                               Map<Integer, Integer> productQuantityMap, 
                                               String fileName) throws IOException {
        List<Map.Entry<Integer, Integer>> list = new ArrayList<>(productQuantityMap.entrySet());
        list.sort((e1, e2) -> Integer.compare(e2.getValue(), e1.getValue())); // Descending order

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileName))) {
            // Note: Assignment says "Deben ir el nombre y el precio". Quantity is added for completeness 
            // since the report is about "productos vendidos por cantidad".
            writer.write("NombreProducto;CantidadVendida;PrecioPorUnidad");
            writer.newLine();
            for (Map.Entry<Integer, Integer> entry : list) {
                Product product = productsMap.get(entry.getKey());
                int quantity = entry.getValue();
                writer.write(product.getName() + ";" + quantity + ";" + String.format("%.2f", product.getPricePerUnit()));
                writer.newLine();
            }
        }
    }
}
